"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import deleteindexrequest as shared_deleteindexrequest
from ..shared import deleteindexresponse as shared_deleteindexresponse
from ..shared import status as shared_status
from typing import Optional


@dataclasses.dataclass
class SearchDeleteIndexRequest:
    
    delete_index_request: shared_deleteindexrequest.DeleteIndexRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'name', 'style': 'simple', 'explode': False }})
    r"""index name."""
    project: str = dataclasses.field(metadata={'path_param': { 'field_name': 'project', 'style': 'simple', 'explode': False }})
    r"""Tigris project name."""
    

@dataclasses.dataclass
class SearchDeleteIndexResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    delete_index_response: Optional[shared_deleteindexresponse.DeleteIndexResponse] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    status: Optional[shared_status.Status] = dataclasses.field(default=None)
    r"""Default error response"""
    