"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import createappkeyrequest as shared_createappkeyrequest
from ...models.shared import createappkeyresponse as shared_createappkeyresponse
from ...models.shared import status as shared_status
from typing import Optional


@dataclasses.dataclass
class TigrisCreateAppKeyRequest:
    create_app_key_request: shared_createappkeyrequest.CreateAppKeyRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    project: str = dataclasses.field(metadata={'path_param': { 'field_name': 'project', 'style': 'simple', 'explode': False }})
    r"""Project name"""
    



@dataclasses.dataclass
class TigrisCreateAppKeyResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    create_app_key_response: Optional[shared_createappkeyresponse.CreateAppKeyResponse] = dataclasses.field(default=None)
    r"""OK"""
    status: Optional[shared_status.Status] = dataclasses.field(default=None)
    r"""Default error response"""
    

