"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import dropcollectionrequest as shared_dropcollectionrequest
from ...models.shared import dropcollectionresponse as shared_dropcollectionresponse
from ...models.shared import status as shared_status
from typing import Optional


@dataclasses.dataclass
class TigrisDropCollectionRequest:
    collection: str = dataclasses.field(metadata={'path_param': { 'field_name': 'collection', 'style': 'simple', 'explode': False }})
    r"""Collection name to delete."""
    drop_collection_request: shared_dropcollectionrequest.DropCollectionRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    project: str = dataclasses.field(metadata={'path_param': { 'field_name': 'project', 'style': 'simple', 'explode': False }})
    r"""Project name whose db is under target to delete collection."""
    



@dataclasses.dataclass
class TigrisDropCollectionResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    drop_collection_response: Optional[shared_dropcollectionresponse.DropCollectionResponse] = dataclasses.field(default=None)
    r"""OK"""
    status: Optional[shared_status.Status] = dataclasses.field(default=None)
    r"""Default error response"""
    

