"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import deleterequest as shared_deleterequest
from ...models.shared import deleteresponse as shared_deleteresponse
from ...models.shared import status as shared_status
from typing import Optional


@dataclasses.dataclass
class TigrisDeleteRequest:
    delete_request: shared_deleterequest.DeleteRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    collection: str = dataclasses.field(metadata={'path_param': { 'field_name': 'collection', 'style': 'simple', 'explode': False }})
    r"""Collection name where to insert documents."""
    project: str = dataclasses.field(metadata={'path_param': { 'field_name': 'project', 'style': 'simple', 'explode': False }})
    r"""Project name whose db is under target to delete documents."""
    



@dataclasses.dataclass
class TigrisDeleteResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    delete_response: Optional[shared_deleteresponse.DeleteResponse] = dataclasses.field(default=None)
    r"""OK"""
    status: Optional[shared_status.Status] = dataclasses.field(default=None)
    r"""Default error response"""
    

