"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses



@dataclasses.dataclass
class QuotaUsageRequest:
    r"""Request current namespace quota usage"""
    

